### ISSUE TITLE
bad request on on microsoft login with error on shell

### ISSUE THREAD

**Issue by emb-karan** [AngellusMortis/django_microsoft_auth#439] opened 2021-01-09 22:48 UTC
could verify id_token sig: It is required that you pass in a value for the "algorithms" argument when calling decode().
Bad Request: /microsoft/auth-callback/
>> "POST /microsoft/auth-callback/ HTTP/1.1" 400 790

**Comment by AngellusMortis** [comment] 2021-01-09 22:50
Dupe of #431

**Closed by AngellusMortis** 2021-01-09 22:50 UTC

**Comment by emb-karan** [comment] 2021-01-09 23:31
![image](https://user-images.githubusercontent.com/52854880/104110746-9a5fb100-5300-11eb-8037-c73b319ae72b.png)

I have fixed the algorithm typo error in microsoft_auth/client.py, but still, I am getting the same error

**Comment by emb-karan** [comment] 2021-01-09 23:42
Alright, I got it, went to Pyjwt doc https://pyjwt.readthedocs.io/en/stable/usage.html

code on line 149 should like this

  ```
          claims = jwt.decode(
                token,
                public_key,
                algorithms=["RS256"], # correction needed here
                audience=self.config.MICROSOFT_AUTH_CLIENT_ID,
            )

```
