### ISSUE TITLE
UnboundLocalError: local variable 'jwk' referenced before assignment in client.py

### ISSUE THREAD

**Issue by chenbr** [AngellusMortis/django_microsoft_auth#409] opened 2020-05-15 23:08 UTC
I'm getting a value error for the jwk key, even though the key (kid) is there. 

putting print statements in the below proves it there. 

116     def get_claims(self, allow_refresh=True):
117         if self.token is None:
118             return None
119
120         token = self.token["id_token"].encode("utf8")
121         print (token)
122
123         kid = jwt.get_unverified_header(token)["kid"]
124         public_key = None
125         for key in self.jwks:
126             print (kid)
127             if kid == key["kid"]:
128                 jwk = key
129                 break
130
131         if jwk is None:
132             if allow_refresh:
133                 logger.warn(
134                     "could not find public key for id_token, "
135                     "refreshing OIDC config"
136                 )
137                 cache.delete(CACHE_KEY_JWKS)
138                 cache.delete(CACHE_KEY_OPENID)
139
140                 return self.get_claims(allow_refesh=False)

Screenshot:
![image](https://user-images.githubusercontent.com/4851378/82102971-481db000-96df-11ea-9046-1abb959b5696.png)

The jwt has all the right info.. so i'm kid of lost as to where this is breaking.. i can sent over some more screenshots but didnt want to post more sensitive info here..

**Comment by AngellusMortis** [comment] 2020-05-15 23:11
Dupe of #292. Fixed by #350

**Closed by AngellusMortis** 2020-05-15 23:11 UTC

**Comment by torfeld6** [comment] 2020-05-26 12:00
@AngellusMortis Version 2.3.1 does not include #350. When are you planing to release the bugfix?
