### ISSUE TITLE
Spelling typo

### ISSUE THREAD

**Issue by BhavinPanch** [AngellusMortis/django_microsoft_auth#429] opened 2020-12-23 13:45 UTC
https://github.com/AngellusMortis/django_microsoft_auth/blob/caf419afba2d523395bf4ecfa4539429ef991503/microsoft_auth/client.py#L154

**Comment by georgethomasuk** [comment] 2020-12-23 14:31
Duplicate of #431 for which I've just raised a PR to fix

**Closed** 2021-01-09 22:49 UTC
